# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dafc03d552f86aa42047d9238da11dc38b405555e898c515113280c44460142dea82b0fe9db9a2be7797fe4c4c73337a1aa7e51db585628e97a75b9e9c23e668

test:
  secret_key_base: 0ec5c288b6215ddd0764d9ccfe6e40e271f07dc848ab9e8179f5783ec0b24254f3001e0bf2b3230175836b022ce0fabb74126127d455d9ebff18bbb397a2f216

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
